<?php

namespace App\Services;

use Illuminate\Support\Str;
use Illuminate\Support\Facades\File;
use App\Game\Interfaces\Movable;

class AdapterGenerator
{
    protected string $adaptersNamespace = 'App\AutoGenerated';

    public function generate(string $interfaceName): string
    {
        $reflection = new \ReflectionClass($interfaceName);
        
        if (!$reflection->isInterface()) {
            throw new \InvalidArgumentException("{$interfaceName} must be an interface");
        }

        $adapterName = $this->adaptersNamespace . '\\' . $reflection->getShortName() . 'Adapter';
        
        if (class_exists($adapterName)) {
            return $adapterName;
        }

        $methodsCode = [];
        foreach ($reflection->getMethods() as $method) {
            $methodsCode[] = $this->generateMethodCode($method);
        }

        $classCode = $this->generateClassCode($adapterName, $interfaceName, $methodsCode);

        // Создаем директорию, если нужно
        $directory = app_path('AutoGenerated');
        if (!File::exists($directory)) {
            File::makeDirectory($directory);
        }

        // Сохраняем класс в файл
        $filename = $directory . '/' . $reflection->getShortName() . 'Adapter.php';
        File::put($filename, "<?php\n\nnamespace {$this->adaptersNamespace};\n\n{$classCode}");

        // Подключаем файл
        require_once $filename;

        return $adapterName;
    }

    protected function generateClassCode(string $className, string $interfaceName, array $methods): string
    {
        $shortClassName = Str::afterLast($className, '\\');
        $shortInterfaceName = Str::afterLast($interfaceName, '\\');
        $methodsCode = implode("\n\n", $methods);
        
        return <<<CODE
class $shortClassName implements \\$interfaceName
{
    protected \$obj;

    public function __construct(\$obj)
    {
        \$this->obj = \$obj;
    }

$methodsCode
}
CODE;
    }

    protected function generateMethodCode(\ReflectionMethod $method): string
    {
        $methodName = $method->getName();
        $parameters = [];
        $paramsForIoC = [];
        
        foreach ($method->getParameters() as $param) {
            $paramStr = '';
            if ($param->hasType()) {
                $paramStr .= $param->getType() . ' ';
            }
            $paramStr .= '$' . $param->getName(); // Убрал экранирование
            
            if ($param->isDefaultValueAvailable()) {
                $paramStr .= ' = ' . var_export($param->getDefaultValue(), true);
            }
            
            $parameters[] = $paramStr;
            $paramsForIoC[] = '$' . $param->getName(); // Убрал экранирование
        }
        
        $parametersStr = implode(', ', $parameters);
        $paramsForIoCStr = $paramsForIoC ? ', ' . implode(', ', $paramsForIoC) : '';
        
        $returnType = $method->getReturnType();
        $returnStr = $returnType ? ': ' . $returnType : '';
        
        if ($returnType && $returnType->getName() === 'void') {
            return <<<METHOD
    public function $methodName($parametersStr)$returnStr
    {
        \app('ioc')->resolve("{$method->getDeclaringClass()->getName()}:$methodName", \$this->obj$paramsForIoCStr)->execute();
    }
METHOD;
        } else {
            return <<<METHOD
    public function $methodName($parametersStr)$returnStr
    {
        return \app('ioc')->resolve("{$method->getDeclaringClass()->getName()}:$methodName", \$this->obj$paramsForIoCStr);
    }
METHOD;
        }
    }
}