<?php

namespace App\AutoGenerated;

class MovableAdapter implements \App\Game\Interfaces\Movable
{
    protected $obj;

    public function __construct($obj)
    {
        $this->obj = $obj;
    }

    public function getPosition(): ?array
    {
        return \app('ioc')->resolve("App\Game\Interfaces\Movable:getPosition", $this->obj);
    }

    public function getVelocity(): ?array
    {
        return \app('ioc')->resolve("App\Game\Interfaces\Movable:getVelocity", $this->obj);
    }

    public function setPosition(array $position): void
    {
        \app('ioc')->resolve("App\Game\Interfaces\Movable:setPosition", $this->obj, $position)->execute();
    }
}